version: '3.7'

volumes:
  yuky_db_vol:

networks:
  yuky:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yuky-be
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - yuky
    depends_on:
      - db
      - nginx
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yuky-fe
    restart: unless-stopped
    working_dir: /frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    networks:
      - yuky

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: yuky-ws
    restart: unless-stopped
    working_dir: /websocket
    ports:
      - "3000:3000"
    volumes:
      - ./websocket:/websocket
    networks:
      - yuky

  nginx:
    image: nginx:alpine
    container_name: yuky-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - yuky
  
  db:
    image: mysql:latest
    container_name: yuky-db
    restart: unless-stopped
    environment: 
      MYSQL_DATABASE: yuky
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - yuky_db_vol:/var/lib/mysql
    networks:
      - yuky