version: '3.7'

volumes:
  yuky_db_vol:

networks:
  yuky:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yuky-be
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - yuky
    volumes:
      - ./backend/.env:/var/www/.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: yuky-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - db
    networks:
      - yuky
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yuky-fe
    restart: unless-stopped
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - yuky

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: yuky-ws
    restart: unless-stopped
    ports:
      - "1000:1000"
    networks:
      - yuky
  
  db:
    image: mysql:8.0
    container_name: yuky-db
    restart: unless-stopped
    environment: 
      MYSQL_DATABASE: yuky
      MYSQL_ROOT_PASSWORD: root
      # Optional: You can remove these if not using non-root users
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - yuky_db_vol:/var/lib/mysql
    networks:
      - yuky